### ISSUE TITLE
[question] - how to calibrate sound card and setting output level

### ISSUE THREAD

**Issue by andmarti1424** [mbrennwa/mataa#4]
Hello Matt. Regarding your MATAA software I have a couple of questions:

1. how can I specify output level when emitting a signal like this:
s = mataa_signal_generator(’square’,96000,0.1,1000);
​res = mataa_measure_signal_response(s,96000);

to say 1Vpp..?

2. how can I calibrate the output signal of my sound card, so that when doing the previous, signal would be exactly 1Vpp, and not more, not less??

Thanks!
I really hope this software how help me with the analisys of my tube amp!

Btw, what external sound card would you recommend? I only have the integrated one of my laptop. And that seems to only support 44100 sample rate..

**Comment by mbrennwa** [comment]
Hi Andrés

I have recently worked on the calibration of the signal levels in MATAA 
quite a bit. The calibration (inlcuding units!) works fine for my 
purposes, but I have not written any documentation for it except the 
help texts in the relevant functions. I'd recommend you to take a look 
at the help text and example of the mataa_signal_calibrate_DUTout 
function (and also the mataa_signal_calibrate_DUTin) to get a rough 
idea of the signal calibration and unit conversion in MATAA.

The “conversion factors” required to convert a signal from the 
digital domain (ranging from -1.0 to +1.0) to a real world signal (for 
example -2.6 to +2.6 Volts at the output of your soundcard) need to be 
specified in a calibration file. It’s probably best to study some of 
the files given in the mataa/calibration folder. The 
“GENERIC_DAC.txt” calibration file might be very similar to what 
you would need in your example. It's probably best to copy 
"GENEREIC_DAC.txt" to a new file (e.g, "ANDRES_LAPTOP_DAC.txt") and 
edit this with the right information / conversion factor.

To determine the value of the conversion factor from digital level to 
real-world voltage level, you could use MATAA to play a full-scale sine 
wave on your soundcard output and measure the AC voltage at the sound 
output. A typical DVM set to AC may give sufficiently accurate results 
(usually RMS values, so multiply by 1.414 to get the zero-to-peak 
amplitude). Note that especially cheaper DVMs may be accurate only at 
mains frequencies (50 r 60 Hz), so it might be a good idea to try 
different frequencies. Or you could use an oscilloscope to read the 
signal amplitude at the soundcard output.

Note that for reasons of backwards-compatibility with older MATAA 
scripts, the mataa_signal_generator always takes an input signal in 
"digital units", not in Volts or other real-world units. An input 
signal with values ranging from -1 to +1 will result in the full 
voltage amplitude at the soundcard output. But you can use the 
mataa_signal_calibrate_DUTin function to determine a factor to 
attenuate the "digital units" signal, so that you'll get the desired 
voltage amplitude at the soundcard output. Here's an example using the 
"GENERIC_DAC.txt" calibration file (note that I haven't tested this 
example properly):

fs = 44100;
S = mataa_signal_generator('square',fs,0.1,1000);
S0 = max(abs(S)); % amplitude of S (digital domain)
X = mataa_signal_calibrate_DUTin (S0,fs,'GENERIC_CHAIN_DIRECT.txt'); % 
determine voltage amplitude at soundcard (DAC) output corresponding to 
S0
c = S0/X; % factor to convert signal amplitude between digital domain 
and voltage at soundcard output
res = mataa_measure_signal_response(c*S,fs); % play S on soundcard, 
should give 1.0V-peak amplitude at soundcard output

This example is bit too complicated for my taste. It would be much 
simpler if it were possible to use mataa_measure_signal_response(...) 
with an input signal that reflects the real-world voltage signal at the 
soundcard output (not the digital domain signal). I'll see if I can 
make this work without breaking the backwards compatibility of 
mataa_measure_signal_response.

With respect to a recommendation of a soundcard it really depends on 
what you need or want. Do you need sample rates higher than 96kHz? Do 
you need a built-in microphone amplifier? Some USB soundcards provide 
pretty good audio quality (distortion, noise), others or just ok, most 
of them are fine for looudspeaker testing. As far as I can tell, most 
USB soundcards are targeted at music production, and they often have 
potentiometers to set the signal levels. This may be fine for music, 
but it can be a nuisance for audio testing, where repeatability of the 
level settings is important. The Audio Ranger by Jan Didden may be 
useful in this regard (but I have no experience with it). I recently 
got an RTX6001 audio analyser, which is essentially a "soundcard" 
targeted at audio analysis. This is very good so far! The audio 
performance is extremely good, and it has well-defined switchable level 
ranges. Here's a link that has a few measurements I made with the 
RTX6001 and MATAA: 
http://www.diyaudio.com/wiki/Tutorial:_How_to_use_the_RTX6001_audio_analyzer_in_real_world_audio_tests

Sorry for this somewhat long reply... I should write this down in the 
MATAA documentation.

Matthias

**Comment by andmarti1424** [comment]
Hello. Thanks for your reply. I will do some tests as soon as I can. In the meantime you can close this.

**Comment by mbrennwa** [comment]
I just tried a few things in the code. I haven't tested this properly, but please try out my change in the mataa_measure_signal_response(...) function that should allow setting the signal level at the analog output. Here's an example to try:

fs = 44100; % sample rate
[s,t] = mataa_signal_generator ('sine',fs,0.2,1000); % test signal, ranging from -1 to +1
s = 1.8 * s; % change amplitude of test signal to 1.8 (Volts)
[out,in,t,out_unit,in_unit] = mataa_measure_signal_response(s,fs,0.1,1,1,'GENERIC_CHAIN_DIRECT.txt','Volt'); % this should produce an 1.8V-pk sine signal at the DAC output

Note the last argument in the mataa_measure_signal_response(...) call. It specifies the unit of the test signal data (s). This is combined with the data in the calibration file in order to get the correct amplitude (voltage) at the DAC output.

Let me know if / how that works out.

**Comment by mbrennwa** [comment]
I have been using MATAA with calibrated levels of input and output levels for a while now. The documentation is available in the m-files, and some more general  description in the manual.

There is also a new tool in MATAA that allows automatic level calibration with the RTX 6001 audio analyser.
